version: '3'

services:
  mysql:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    command:
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
    volumes:
      - ./sql:/docker-entrypoint-initdb.d